import { getAdminDb } from './firebase-admin'

/**
 * Server-only helpers for the per-couple "connect your own Google Drive"
 * integration (see the guest list "Connect Google Drive" panel and
 * app/composables/useGoogleDrive.ts on the client).
 *
 * Design: each wedding gets ONE Firestore doc at driveConnections/{weddingId}
 * holding that couple's own OAuth refresh token, current access token, and
 * the Drive folder we upload exports into. This collection is never exposed
 * to the client Firestore SDK (see firestore.rules - `allow read, write: if
 * false`), so it is only ever readable/writable through the Firebase Admin
 * SDK from these server routes. Plain fetch() is used throughout instead of
 * the `googleapis` npm package to avoid a heavy dependency for what is just
 * a handful of REST calls.
 */

const TOKEN_URL = 'https://oauth2.googleapis.com/token'
const REVOKE_URL = 'https://oauth2.googleapis.com/revoke'
const USERINFO_URL = 'https://www.googleapis.com/oauth2/v3/userinfo'
const DRIVE_FILES_URL = 'https://www.googleapis.com/drive/v3/files'
const DRIVE_UPLOAD_URL = 'https://www.googleapis.com/upload/drive/v3/files'

// Fixed connection-id used for the ADMIN's own, single, wide Google Drive
// connection (as opposed to a per-wedding one keyed by weddingId) - reuses
// the exact same driveConnections/{id} document shape and OAuth callback
// route by simply passing this constant wherever a weddingId would go, so
// no new Firestore collection or Google OAuth redirect URI is needed. See
// server/utils/guest-sync.ts and server/api/admin/drive/*.
export const ADMIN_DRIVE_CONNECTION_ID = 'admin'

// Top-level folder name (in the admin's own connected Drive) that every
// wedding's guest-list exports sync into, one subfolder per wedding - see
// server/utils/guest-sync.ts.
export const RSVP_LISTS_FOLDER_NAME = 'RSVP Lists'

export interface DriveConnectionDoc {
  weddingId: string
  ownerUid: string
  connected: boolean
  refreshToken?: string
  accessToken?: string
  accessTokenExpiresAt?: number
  driveEmail?: string
  folderId?: string
  folderLink?: string
  createdAt?: string
  updatedAt?: string
}

function driveConfig() {
  const config = useRuntimeConfig()
  const clientId = config.googleClientId as string
  const clientSecret = config.googleClientSecret as string
  const redirectUri = config.googleRedirectUri as string
  if (!clientId || !clientSecret || !redirectUri) {
    throw createError({
      statusCode: 500,
      statusMessage: 'Google Drive is not configured on this server yet (missing NUXT_GOOGLE_CLIENT_ID / NUXT_GOOGLE_CLIENT_SECRET / NUXT_GOOGLE_REDIRECT_URI).'
    })
  }
  return { clientId, clientSecret, redirectUri }
}

export function driveConnectionRef(weddingId: string) {
  return getAdminDb().doc(`driveConnections/${weddingId}`)
}

export async function getDriveConnection(weddingId: string): Promise<DriveConnectionDoc | null> {
  const snap = await driveConnectionRef(weddingId).get()
  return snap.exists ? (snap.data() as DriveConnectionDoc) : null
}

/**
 * Step 1 of the OAuth flow - builds the consent-screen URL. `state` is an
 * opaque, single-use token generated by the caller and stashed in
 * driveOAuthStates/{state} so the callback (an unauthenticated browser
 * redirect from Google - no Authorization header available) can look up
 * which wedding this belongs to.
 */
export function buildGoogleAuthUrl(state: string): string {
  const { clientId, redirectUri } = driveConfig()
  const params = new URLSearchParams({
    client_id: clientId,
    redirect_uri: redirectUri,
    response_type: 'code',
    scope: 'https://www.googleapis.com/auth/drive.file https://www.googleapis.com/auth/userinfo.email',
    access_type: 'offline',
    prompt: 'consent',
    state
  })
  return `https://accounts.google.com/o/oauth2/v2/auth?${params.toString()}`
}

/**
 * Step 2 - exchanges the authorization code Google redirected back with for
 * a refresh + access token pair.
 */
export async function exchangeCodeForTokens(code: string): Promise<{ accessToken: string; refreshToken: string; expiresIn: number }> {
  const { clientId, clientSecret, redirectUri } = driveConfig()
  const res = await fetch(TOKEN_URL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: new URLSearchParams({
      code,
      client_id: clientId,
      client_secret: clientSecret,
      redirect_uri: redirectUri,
      grant_type: 'authorization_code'
    })
  })
  if (!res.ok) {
    throw createError({ statusCode: 502, statusMessage: `Google rejected the authorization code: ${await res.text()}` })
  }
  const data = await res.json() as { access_token: string; refresh_token?: string; expires_in: number }
  if (!data.refresh_token) {
    // Happens if the couple had already granted consent before without a
    // dangling connection being revoked - Google only issues a refresh
    // token on first consent (or when prompt=consent forces re-consent,
    // which buildGoogleAuthUrl always sets, so this should be rare).
    throw createError({ statusCode: 502, statusMessage: 'Google did not return a refresh token - please disconnect any prior access at https://myaccount.google.com/permissions and try connecting again.' })
  }
  return { accessToken: data.access_token, refreshToken: data.refresh_token, expiresIn: data.expires_in }
}

async function refreshAccessToken(refreshToken: string): Promise<{ accessToken: string; expiresIn: number }> {
  const { clientId, clientSecret } = driveConfig()
  const res = await fetch(TOKEN_URL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: new URLSearchParams({
      refresh_token: refreshToken,
      client_id: clientId,
      client_secret: clientSecret,
      grant_type: 'refresh_token'
    })
  })
  if (!res.ok) {
    throw createError({ statusCode: 502, statusMessage: `Could not refresh the Google Drive connection: ${await res.text()}` })
  }
  const data = await res.json() as { access_token: string; expires_in: number }
  return { accessToken: data.access_token, expiresIn: data.expires_in }
}

export async function fetchGoogleEmail(accessToken: string): Promise<string> {
  const res = await fetch(USERINFO_URL, { headers: { Authorization: `Bearer ${accessToken}` } })
  if (!res.ok) return ''
  const data = await res.json() as { email?: string }
  return data.email || ''
}

/**
 * Returns a valid (non-expired) access token for this wedding's Drive
 * connection, refreshing it first if needed. Throws if the wedding has
 * never connected Drive.
 */
export async function getValidAccessToken(weddingId: string): Promise<{ accessToken: string; connection: DriveConnectionDoc }> {
  const connection = await getDriveConnection(weddingId)
  if (!connection || !connection.connected || !connection.refreshToken) {
    throw createError({ statusCode: 409, statusMessage: 'Google Drive is not connected for this wedding yet.' })
  }

  const now = Date.now()
  if (connection.accessToken && connection.accessTokenExpiresAt && connection.accessTokenExpiresAt - 60_000 > now) {
    return { accessToken: connection.accessToken, connection }
  }

  const refreshed = await refreshAccessToken(connection.refreshToken)
  const accessTokenExpiresAt = now + refreshed.expiresIn * 1000
  await driveConnectionRef(weddingId).update({ accessToken: refreshed.accessToken, accessTokenExpiresAt, updatedAt: new Date().toISOString() })
  return { accessToken: refreshed.accessToken, connection: { ...connection, accessToken: refreshed.accessToken, accessTokenExpiresAt } }
}

/**
 * Finds this app's export folder in the couple's Drive by name, or creates
 * it the first time. Using drive.file scope means we can only ever see
 * files/folders this app itself created - never the rest of their Drive.
 */
export async function ensureAppFolder(accessToken: string, folderName: string): Promise<{ folderId: string; folderLink: string }> {
  const q = encodeURIComponent(`name = '${folderName.replace(/'/g, "\\'")}' and mimeType = 'application/vnd.google-apps.folder' and trashed = false`)
  const searchRes = await fetch(`${DRIVE_FILES_URL}?q=${q}&fields=files(id,webViewLink)&spaces=drive`, {
    headers: { Authorization: `Bearer ${accessToken}` }
  })
  if (searchRes.ok) {
    const data = await searchRes.json() as { files?: Array<{ id: string; webViewLink?: string }> }
    if (data.files && data.files.length > 0) {
      const found = data.files[0]!
      return { folderId: found.id, folderLink: found.webViewLink || `https://drive.google.com/drive/folders/${found.id}` }
    }
  }

  const createRes = await fetch(`${DRIVE_FILES_URL}?fields=id,webViewLink`, {
    method: 'POST',
    headers: { Authorization: `Bearer ${accessToken}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ name: folderName, mimeType: 'application/vnd.google-apps.folder' })
  })
  if (!createRes.ok) {
    throw createError({ statusCode: 502, statusMessage: `Could not create the Google Drive folder: ${await createRes.text()}` })
  }
  const created = await createRes.json() as { id: string; webViewLink?: string }
  return { folderId: created.id, folderLink: created.webViewLink || `https://drive.google.com/drive/folders/${created.id}` }
}

/**
 * Always CREATES a new file in the given folder via a simple multipart
 * request (avoiding any dependency on the googleapis SDK). Drive allows
 * duplicate names, so calling this repeatedly piles up a new file each
 * time - most callers want upsertFileInFolder() below instead, which keeps
 * exactly one file per name by updating it in place.
 */
export async function uploadFileToFolder(
  accessToken: string,
  folderId: string,
  filename: string,
  mimeType: string,
  content: Uint8Array | string
): Promise<{ fileId: string; webViewLink: string }> {
  const boundary = `wcexport-${Date.now()}`
  const metadata = JSON.stringify({ name: filename, parents: [folderId] })
  const bodyContent = typeof content === 'string' ? content : Buffer.from(content).toString('binary')

  const multipartBody =
    `--${boundary}\r\n` +
    `Content-Type: application/json; charset=UTF-8\r\n\r\n${metadata}\r\n` +
    `--${boundary}\r\n` +
    `Content-Type: ${mimeType}\r\n\r\n${bodyContent}\r\n` +
    `--${boundary}--`

  const res = await fetch(`${DRIVE_UPLOAD_URL}?uploadType=multipart&fields=id,webViewLink`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${accessToken}`,
      'Content-Type': `multipart/related; boundary=${boundary}`
    },
    body: Buffer.from(multipartBody, 'binary')
  })
  if (!res.ok) {
    throw createError({ statusCode: 502, statusMessage: `Could not upload to Google Drive: ${await res.text()}` })
  }
  const data = await res.json() as { id: string; webViewLink?: string }
  return { fileId: data.id, webViewLink: data.webViewLink || `https://drive.google.com/file/d/${data.id}/view` }
}

/**
 * Like uploadFileToFolder(), but keeps exactly ONE file per name inside the
 * folder: if a file with this exact name already exists there, its content
 * is updated in place (same fileId, same Drive link) instead of creating a
 * new one. This is what makes the Drive folder "auto-update" rather than
 * piling up a new timestamped export every time a guest RSVPs.
 */
export async function upsertFileInFolder(
  accessToken: string,
  folderId: string,
  filename: string,
  mimeType: string,
  content: Uint8Array | string
): Promise<{ fileId: string; webViewLink: string }> {
  const q = encodeURIComponent(`name = '${filename.replace(/'/g, "\\'")}' and '${folderId}' in parents and trashed = false`)
  const searchRes = await fetch(`${DRIVE_FILES_URL}?q=${q}&fields=files(id,webViewLink)&spaces=drive`, {
    headers: { Authorization: `Bearer ${accessToken}` }
  })

  let existingFileId = ''
  if (searchRes.ok) {
    const data = await searchRes.json() as { files?: Array<{ id: string; webViewLink?: string }> }
    if (data.files && data.files.length > 0) existingFileId = data.files[0]!.id
  }

  if (!existingFileId) {
    return uploadFileToFolder(accessToken, folderId, filename, mimeType, content)
  }

  const bodyContent = typeof content === 'string' ? Buffer.from(content, 'utf8') : Buffer.from(content)
  const res = await fetch(`https://www.googleapis.com/upload/drive/v3/files/${existingFileId}?uploadType=media&fields=id,webViewLink`, {
    method: 'PATCH',
    headers: { Authorization: `Bearer ${accessToken}`, 'Content-Type': mimeType },
    body: bodyContent
  })
  if (!res.ok) {
    throw createError({ statusCode: 502, statusMessage: `Could not update the Google Drive file: ${await res.text()}` })
  }
  const data = await res.json() as { id: string; webViewLink?: string }
  return { fileId: data.id, webViewLink: data.webViewLink || `https://drive.google.com/file/d/${data.id}/view` }
}

/**
 * Finds (or creates) a subfolder by name inside a given parent folder - used
 * to give each wedding its own "{Bride} & {Groom} (slug)" subfolder inside
 * the admin's single top-level "RSVP Lists" folder.
 */
export async function ensureSubfolder(
  accessToken: string,
  parentFolderId: string,
  subfolderName: string
): Promise<{ folderId: string; folderLink: string }> {
  const q = encodeURIComponent(
    `name = '${subfolderName.replace(/'/g, "\\'")}' and '${parentFolderId}' in parents and mimeType = 'application/vnd.google-apps.folder' and trashed = false`
  )
  const searchRes = await fetch(`${DRIVE_FILES_URL}?q=${q}&fields=files(id,webViewLink)&spaces=drive`, {
    headers: { Authorization: `Bearer ${accessToken}` }
  })
  if (searchRes.ok) {
    const data = await searchRes.json() as { files?: Array<{ id: string; webViewLink?: string }> }
    if (data.files && data.files.length > 0) {
      const found = data.files[0]!
      return { folderId: found.id, folderLink: found.webViewLink || `https://drive.google.com/drive/folders/${found.id}` }
    }
  }

  const createRes = await fetch(`${DRIVE_FILES_URL}?fields=id,webViewLink`, {
    method: 'POST',
    headers: { Authorization: `Bearer ${accessToken}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ name: subfolderName, mimeType: 'application/vnd.google-apps.folder', parents: [parentFolderId] })
  })
  if (!createRes.ok) {
    throw createError({ statusCode: 502, statusMessage: `Could not create the Google Drive subfolder: ${await createRes.text()}` })
  }
  const created = await createRes.json() as { id: string; webViewLink?: string }
  return { folderId: created.id, folderLink: created.webViewLink || `https://drive.google.com/drive/folders/${created.id}` }
}

export async function revokeDriveConnection(weddingId: string): Promise<void> {
  const connection = await getDriveConnection(weddingId)
  if (connection?.refreshToken) {
    try {
      await fetch(`${REVOKE_URL}?token=${encodeURIComponent(connection.refreshToken)}`, { method: 'POST' })
    } catch {
      // Best-effort - still clear our own record even if Google's revoke call fails.
    }
  }
  await driveConnectionRef(weddingId).set({
    weddingId,
    ownerUid: connection?.ownerUid || '',
    connected: false,
    updatedAt: new Date().toISOString()
  }, { merge: true })
}
